Select * from customer limit 20

-- Q1. What is the total revenue generated by male vs. female customers?
 Select gender,SUM(purchase_amount) as revenue 
 from customer
 group by gender

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
Select customer_id,purchase_amount
from customer
where discount_applied='Yes' and purchase_amount >= (Select AVG(purchase_amount) from customer)
-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased , Round(AVG(review_rating),2) as "Average_review_rating"
from customer
group by item_purchased 
order by AVG(review_rating) desc
limit 5;

-- Q4. Compare the average purchase amounts between Standard and Express shipping.
select shipping_type,Round(AVG(purchase_amount),2)
from customer
where shipping_type in ("Standard","Express")
group by  shipping_type

-- Q5. Do subscribed customers spend more?
-- Compare average spend and total revenue between subscribers and non-subscribers.
Select subscription_status, COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as average_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order  by  total_revenue,average_spend desc;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes'  THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases,
-- and show the count of each segment.
-- customer_type is the CTE name
-- it behaves like a temporary table while  the query runs
-- common table expressions

with customer_type as(
select customer_id,previous_purchases,
CASE
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
from customer 
)

select customer_segment , COUNT(*) as "Number of Customers"
from customer_type
group by customer_segment;


 /*with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment; */

-- Q8. What are the top 3 most purchased products within each category?
-- will use window function and cte  as well
-- RANK and DENSE_RANK give the same rank to tied values, whereas ROW_NUMBER ensures a distinct ranking needed for top-3 selection.
-- -- ROW_NUMBER is used to rank items within each category based on total orders to find top 3 items
-- -- CTE is used to calculate item-wise total orders and rankings before filtering top items

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (
               PARTITION BY category
               ORDER BY COUNT(customer_id) DESC
           ) AS item_rank
    FROM customer
    GROUP BY category, item_purchased
)

SELECT item_rank,
       category,
       item_purchased,
       total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases)
-- also likely to subscribe?
Select subscription_status, COUNT(customer_id) as repeat_buyers 
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contribution of each age group?
select age_group , COUNT(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;
